### ISSUE TITLE
\Assert\that() method chaining not found

### ISSUE THREAD

**Issue by SpacefulSpecies** [beberlei/assert#122]
I use this library for a long time, and never had issues with it in Phpstorm, until now. Not a single method of the AssertionChain gets recognised anymore.

```php
\Assert\that($name)->string(); // Method 'string' not found in class
```
I might have to redirect this issue to Phpstorm itself, since I'm not sure if I have this problem since a newer version of this library or since the Phpstorm 9 update. But I ask it here first, because the following snippet (which uses the same mechanics) works like a charm:

```php
/**
 * @method Foo bar()
 */
class Foo {
}

/**
 * @return Foo
 */
function test()
{
    return new Foo();
}

test()->bar(); // method is recognised
```

**Comment by SpacefulSpecies** [comment]
oh forgot something important to mention: the code works, it's just Phpstorm that starts to complain where it didn't complain before.

**Comment by AntonStoeckl** [comment]
I have the same issue for quite some time now, I'm always using the EAP versions from PhpStrom.

I'm quite sure the problem is in PhpStorm, not in the Assert Lib.

I got this problem after updateing PhpStrom, the guys in our company not using the EAP version don't have it, and they definitely have the same version of Assert, we do check in our composer.lock

**Comment by SpacefulSpecies** [comment]
Thanks for the information. Now I tested more (I should have done that before comming here) and it is a PhpStorm bug. I created a ticket: https://youtrack.jetbrains.com/issue/WI-28993

This can be closed now.
