### ISSUE TITLE
Integration with the Symfony Validator component

### ISSUE THREAD

**Issue by iainmckay** [beberlei/assert#145]
Hi guys, we wanted to be able to use the assertion library as constraints in the Symfony Validator and couldn't find anything to support this so we wrote our own. It's really just a generate that generates constraint classes and a wrapper to make them work in the validator component.

I thought you might be interested and we'd love some feedback.

https://github.com/MySchoolManagement/assert-constraint

**Comment by rquadling** [comment]
Hi.

There are VERY few devs of this package (me) and so that's probably why no feedback.

I'm cleaning up issues and PRs and see no need to keep this issue open any more.

There are more assertions in master (and soon to be released), so you may want to update your package with that. Maybe as part of a composer post-install script to run your generator, thereby not actually needing to hold onto the constraints directly.

If that doesn't make any sense, let me know.

In the mean time, thank you for taking the time to work with this package.
