### ISSUE TITLE
\Assert\that($object)->methodExists(…) does not pass the correct method parameters

### ISSUE THREAD

**Issue by StanAngeloff** [beberlei/assert#154]
The `methodExists` (and possibly others) are not chained correctly when used with `\Assert\that(…)`:

```php
<?php

class Greet {
    function hello() { return 'Hi!'; }
}

$greeter = new Greet();

echo method_exists($greeter, 'hello'); # => 1

\Assert\that($greeter)->methodExists('hello'); # => fails! Provided "hello" is not a valid object.
```

**Comment by rquadling** [comment]
Confirmed:

The order of the first 2 parameters from the chained invocation is the wrong way around.

Will affect all assertions with more than 1 parameter involved in the assertion (ignoring the `$message` and `$propertyPath` parameters).

Will look into this now.

**Comment by StanAngeloff** [comment]
By design?

**Comment by rquadling** [comment]
```php
    public function testMethodExists()
    {
        Assertion::methodExists('methodExists', new Assertion());
    }
```

This has been like this since inception https://github.com/beberlei/assert/pull/62. I have no further information (only recently joined the project).

I think changing the order at this stage wouldn't be possible due to BC. MAYBE in a version change so the order matched `method_exists()`.

But both Assertion and LazyAssertion follow the same parameter order, so your code would be
```php
<?php
Assertion::methodExists($methodName, $object);
\Assert\that($methodName)->methodExists($object);
```

**Comment by rquadling** [comment]
Potentially ( just thinking out loud ), removing `method_exists` and replacing it with `objectHasMethod` _MAY_ be cleaner.

At this point in time though, I don't think there are plans to do anything on this.
